services:
    backend-dev:
        build: ./habitual/backend
        ports:
            - "9009:9009"
        volumes:
            - ./habitual/backend:/app
        command: ["--reload"]
        profiles: ["dev"]

    backend-prod:
        build: ./habitual/backend
        ports:
            - "9009:9009"
        profiles: ["prod"]