services:
    backend-dev:
        build:
            context: ./habitual/backend
            dockerfile: dev.Dockerfile
        ports:
            - "9009:9009"
        volumes:
            - ./habitual/backend:/app
            # Isolate the container venv from the host venv
            - habitual-backend-venv:/app/.venv
        profiles: ["dev"]

    backend-prod:
        build:
            context: ./habitual/backend
            dockerfile: Dockerfile
        ports:
            - "9009:9009"
        profiles: ["prod"]

volumes:
    habitual-backend-venv:
