services:
    mysql:
        image: mysql:9.4
        ports:
            - "3306:3306"
        volumes:
            - habitual-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_USER: habitual
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
            MYSQL_DATABASE: habitual
        secrets:
            - db_root_password
            - db_password
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$(cat /run/secrets/db_root_password)"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        profiles: ["dev", "prod"]

    backend-dev:
        build:
            context: ./habitual/backend
            dockerfile: dev.Dockerfile
        ports:
            - "9009:9009"
        volumes:
            - ./habitual/backend:/app
            # Isolate the container venv from the host venv
            - habitual-backend-venv:/app/.venv
        environment:
            DB_USER: habitual
            DB_PASSWORD_FILE: /run/secrets/db_password
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: habitual
        secrets:
            - db_password
        depends_on:
            mysql:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://localhost:9009/health"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        profiles: ["dev"]

    backend-prod:
        build:
            context: ./habitual/backend
            dockerfile: Dockerfile
        ports:
            - "9009:9009"
        environment:
            DB_USER: habitual
            DB_PASSWORD_FILE: /run/secrets/db_password
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: habitual
        secrets:
            - db_password
        depends_on:
            mysql:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-fsS", "http://localhost:9009/health"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        profiles: ["prod"]

    frontend-dev:
        build:
            context: ./habitual/frontend
            dockerfile: dev.Dockerfile
        ports:
            - "3003:3003"
        volumes:
            - ./habitual/frontend:/app
        environment:
            API_BASE_INTERNAL: http://backend-dev:9009/api/v1
        depends_on:
            backend-dev:
                condition: service_healthy
        profiles: ["dev"]

    frontend-prod:
        build:
            context: ./habitual/frontend
            dockerfile: Dockerfile
        ports:
            - "3003:3003"
        environment:
            API_BASE_INTERNAL: http://backend-prod:9009/api/v1
        depends_on:
            backend-prod:
                condition: service_healthy
        profiles: ["prod"]

volumes:
    habitual-backend-venv:
    habitual-mysql-data:

secrets:
    db_root_password:
        file: ./habitual/backend/secrets/db_root_password.txt
    db_password:
        file: ./habitual/backend/secrets/db_password.txt
