services:
    backend-dev:
        build: ./habitual/backend
        ports:
            - "9009:9009"
        volumes:
            - ./habitual/backend:/app
            # Isolate the container venv from the host venv
            - habitual-backend-venv:/app/.venv
        command: ["--reload"]
        profiles: ["dev"]

    backend-prod:
        build: ./habitual/backend
        ports:
            - "9009:9009"
        profiles: ["prod"]

volumes:
    habitual-backend-venv:
