import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import { MantineProvider } from "@mantine/core";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <MantineProvider
          forceColorScheme="dark"
          theme={{
            primaryColor: "blue",
            fontFamily: roboto.style.fontFamily,
            defaultRadius: "md",
            components: {
              Button: {
                styles: {
                  root: { boxShadow: "none" },
                },
              },
              ActionIcon: {
                styles: {
                  root: { boxShadow: "none" },
                },
              },
            },
          }}
        >
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
